### ISSUE TITLE
RoleName Global Administrator was in an incorrect format

### ISSUE THREAD

**Issue by janegilring** [JustinGrote/JAz.PIM#6]
I was trying to elevate an Azure AD role in a new environment today, where I ran the following:

```
Install-Module JAz.Pim
Import-Module JAz.Pim

Connect-MgGraph -Scopes 'RoleEligibilitySchedule.Read.Directory','RoleAssignmentSchedule.ReadWrite.Directory'

Select-MgProfile 'beta'
Enable-JAzADRole <tab or shift-enter>
```

Tab-completion worked fine, and generated the following:
`Enable-JAzADRole 'Global Administrator (lAPpYvVpN0KRkAEhdxReECk6SdNuzPFGtcqHa7DlO_U-1-e)'`

However, the command fails with:
```
Line |
  10 |  … roleGuid) { throw "RoleName $roleName was in an incorrect format. It  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | RoleName Global Administrator (lAPpYvVpN0KRkAEhdxReECk6SdNuzPFGtcqHa7DlO_U-1-e) was in an incorrect format. It should have
     | (RoleNameGuid) somewhere in the body. The -RoleName parameter is generally not meant to be entered manually, try <tab> or pipe
     | in objects per the help examples.
```

I then tried piping an object from Get-JAzADRole, this worked (although a different issue is present):
```
(Get-JAzADRole)[1] | Enable-JAzADRole -Justification 'Daily PIM' -Hours 8
Enable-JAzADRole: The following policy rules failed: ["MfaRule"]
```

**Comment by JustinGrote** [comment]
@janegilring thanks for the report, I'm aware of this and am transitioning the AD part of it from the beta API to the v1.0 API, should help.

The MfaRule issue means that you aren't using a user who has done at least one MFA in the session (or doesn't have MFA configured) and your PIM requires it. I plan to make a "nicer" error message for that.

**Comment by janegilring** [comment]
Great. I'll test again when the transition is completed. Until then, piping works fine.

Regarding the MfaRule issue, it worked fine when I used device authentication and signed in from a different device. In the initial attempt, it was automatically authenticating in a pre-authenticated browser which also was behind a public IP excluded from Conditional Access MFA enforcement.

**Comment by JustinGrote** [comment]
@janegilring v0.0.7 is out with the new API, try it out.

**Comment by janegilring** [comment]
Wow, that was fast - will do =)

**Comment by janegilring** [comment]
Worked like a charm

```
Enable-JAzADRole 'Global Administrator (lAPpYvVpN0KRkAEhdxReECk6SdNuzPFGtcqHa7DlO_U-1-e)' -Justification 'Daily PIM' -Hours 8

Action       Status              PrincipalDisplayName         RoleName             Scope     StartDateTime       EndDateTime
------       ------              --------------------         --------             -----     -------------       -----------
selfActivate PendingProvisioning Admin Jan Egil Ring Global Administrator Directory 18.05.2022 16:47:23 19.05.2022 00:47:23
```
